let name = "amanmodi";
console.log(name);
console.log(name[0]);
console.log(name[1]);
console.log(name[2]);
console.log(name[3]);
console.log(name[4]);
console.log(name[5]);
console.log(name[6]);
console.log(name[7]);
console.log(name.length);
let friend = 'haini';
console.log(friend);
// let myfriend = "Sabd';// Dont do this
// console.log(myfriend);
let boy = "aman";
let boy1 = "modi";
let sentence = `${boy1} is a friend of ${boy}`;
console.log(sentence);
// Escape sequence character
// let a = 'aman\'s';
// console.log(a);
// let a = "aman\"s";
// console.log(a);
// let a = "aman's";
// console.log(a);
// let a = "aman\ns";
// console.log(a);
// let a = "aman\rmodi";
// console.log(a);
let a = "aman\ts";
console.log(a);